services:
  postgres:
    image: postgres:14
    container_name: paperlessdb
    restart: no
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: paperlessDb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h 127.0.0.1 -p 5432 -U admin -d paperlessDb"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: paperless-api
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/paperlessDb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_MAIN_BANNER_MODE: console
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8081:8080"

volumes:
  postgres_data:
